#!/usr/bin/env bash
#
# Claude Code PostToolUse(Bash) hook.
#
# Whenever changes are staged (`git add`), regenerate
# .claude/context/RECENT_CHANGES.md with a summary of the current branch —
# commits + diffstat vs `master`, plus staged/unstaged files. The goal: a future
# Claude session (and PR reviewers) can read ONE file to learn what this branch
# changed, instead of diffing the whole tree. The file is auto-staged so it rides
# along in the next commit / PR.
#
# Wired in .claude/settings.json. Receives the tool-call JSON on stdin.

input="$(cat 2>/dev/null || true)"

# Only act when the Bash command was a `git add`. Everything else exits fast.
case "$input" in
  *"git add"*) ;;
  *) exit 0 ;;
esac

root="${CLAUDE_PROJECT_DIR:-$(pwd)}"
cd "$root" 2>/dev/null || exit 0
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || exit 0

# Base branch to diff against (skip that section if it doesn't exist locally).
base="master"
git rev-parse --verify --quiet "$base" >/dev/null 2>&1 || base=""

branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
out=".claude/context/RECENT_CHANGES.md"
mkdir -p "$(dirname "$out")"

{
  echo "# Recent changes — branch \`$branch\`"
  echo
  echo "> Auto-generated by the git-add hook on $(date '+%Y-%m-%d %H:%M %Z')."
  echo "> Read this first to see what this branch changed without diffing every file."
  [ -n "$base" ] && echo "> Base branch: \`$base\`."
  echo

  if [ -n "$base" ]; then
    echo "## Commits ahead of \`$base\`"
    echo '```'
    git log "$base..HEAD" --oneline 2>/dev/null
    echo '```'
    echo
    echo "## Files changed vs \`$base\` (committed)"
    echo '```'
    git diff "$base...HEAD" --stat 2>/dev/null
    echo '```'
    echo
  fi

  # Working tree: staged (index) + unstaged + untracked, in one view.
  # Codes: XY path — X=index (staged), Y=work tree; "??"=untracked, "A"=added,
  # "M"=modified, "D"=deleted, "R"=renamed.
  echo "## Working tree (staged / unstaged / untracked)"
  echo '```'
  git status --short 2>/dev/null
  echo '```'
} > "$out"

# Include the summary itself in the staged set so it rides along in the commit.
# (This runs git directly, not via Claude's Bash tool, so it won't re-trigger the hook.)
git add "$out" >/dev/null 2>&1 || true

exit 0
